name: Daily Commit Updated
on:
  schedule:
    - cron: "0 0 * * *"   # Roz raat 12 baje run hoga
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run workflow
        run: echo "Running workflow"

      - name: Make change
        run: echo "Updated $(date)" >> log.txt

      - name: Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "23f2003724@ds.study.iitm.ac.in"
          git add .
          git diff --cached --quiet || git commit -m "Daily commit"
          git push