name: Daily Commit

permissions:
  contents: write

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f2003724@ds.study.iitm.ac.in step
        run: echo "Updated on $(date)" >> log.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "23f2003724@ds.study.iitm.ac.in"
          git add .
          git commit -m "Daily commit" || echo "No changes"
          git push